name: 'GSA/ansible-rhel-domain'
description: 'ansible role joins a redhat server to a windows domain'
license: cc0-1.0
openSourceProject: 1
governmentWideReuseProject: 1
tags:
    - open-source
    - opensource
    - grace
    - devsecops
    - ansible
contact:
    email: grace-staff@gsa.gov
